export const LOAN_ACTION_TYPES = {
  FETCH_LOAN_START: 'loan/FETCH_LOAN_START',
  FETCH_LOAN_SUCCESS: 'loan/FETCH_LOAN_SUCCESS',
  FETCH_LOAN_FAILED: 'loan/FETCH_LOAN_FAILED',
  FETCH_LOANS_START: 'loan/FETCH_LOANS_START',
  FETCH_LOANS_SUCCESS: 'loan/FETCH_LOANS_SUCCESS',
  FETCH_LOANS_FAILED: 'loan/FETCH_LOANS_FAILED',
};
